### ISSUE TITLE
Incluir categorias com contagem 0 em um intervalo de tempo nas estatísicas

### ISSUE THREAD

**Issue by pedromrnd** [brunorafaeli/bigdata_monitoramento_de_redes_sociais#13]

**Comment by pedromrnd** [comment]
Acho que já sei como resolver.
 val zerosDS = Array((("ibm","cat_teste"),0.0))
 val dZerosDS = ssc.sparkContext.parallelize(zerosDS) // ssc.sparkContext retorna o spark context
val categories_with_zeros = categories.transform(rdd => rdd.union(dZerosDS ))

Só substituir o zerosDS por um array com toadas a categorias zeradas

> **transform(func)**:
> 
> > Return a new DStream by applying a RDD-to-RDD function to every RDD of the source DStream.  This can be used to do arbitrary RDD operations on the DStream.

https://spark.apache.org/docs/1.2.0/streaming-programming-guide.html#transformations-on-dstreams

**Comment by pedromrnd** [comment]
**Correção:**
Na verdade deveria unir antes do reduce

**Comment by Berne023** [comment]
Aparentemente funcionou. Agora ele pega 0.0 em todos os blocos, mesmo quando não tem nenhuma categoria aparecendo. Vou limpar o código e já commito.
